### ISSUE TITLE
routeEnhancers yaml

### ISSUE THREAD

**Issue by jwbdv** [in2code-de/gb_events#5]
hi :-)

 i want to have nice urls using the path_segment field.
 coud you help me to finish it:
 
 routeEnhancers:
  GbEvents:
    type: Plugin
    namespace: tx_gbevents
    routePath: '/{tx_gbevents}'
    aspects:
      tx_gbevents:
        type: PersistedAliasMapper
        tableName: tx_gbevents_domain_model_event
        routeFieldName: path_segment
    defaults:
      tx_gbevents: '0'
 
 thx a lot

**Comment by einpraegsam** [comment]
Please don't use github issues for asking support questions. I would rather ask on stackoverflow or slack for community help.

**Comment by mtness** [comment]
Just found this one after writing my issue, 
a working config can be found hrere:
https://github.com/in2code-de/gb_events/issues/7
or here:
https://stackoverflow.com/questions/78152716/gb-events-working-routing-configuration-typo3
